// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../lib/ready.js', ['ss.ready', 'ss.ready.C'], ['goog.structs.Map']);
