// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../source/server2js.export.js', ['ss.server'], ['ss.server2js', 'ss.Server2js']);
goog.addDependency('../source/server2.js', ['ss.Server2js', 'ss.server2js'], []);
